#######################################################################################
# Book settings
title : sparse-ir
author: Many authors
copyright: "2022"

# Information about where the book exists on the web
description: >-
  Online document for sparse-ir

#######################################################################################
# Execution settings
execute:
  execute_notebooks           : cache
  timeout                     : 120

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar         : false

# #######################################################################################
# Interact link settings

#######################################################################################
# Launch button settings
launch_buttons:
  url: "https://github.com/shinaoka/binder-test.git"
  path_to_book                : src
  branch                      : main
  notebook_interface          : classic
  colab_url: "https://colab.research.google.com"

launch_buttons:
  binderhub_url: "https://mybinder.org"

latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex

# Bibliography settings
bibtex_bibfiles:
  - references.bib

sphinx:
  config:
    bibtex_reference_style: author_year
    language: en

parse:
  myst_substitutions:
      sub3: My _global_ value!
  myst_url_schemes: [mailto, http, https]
 
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
